- name: Install k3s agent
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | \
    K3S_URL=https://{{ k3s_master_ip }}:6443 \
    K3S_TOKEN={{ hostvars[groups['master'][0]]['k3s_token'] }} \
    K3S_NODE_LABEL="node-role.kubernetes.io/worker=true" \
    sh -
